export const actions = {
    MOST_APPEARED_PERSON_LOADED: 'MOST_APPEARED_PERSON_LOADED',
    MOST_APPEARED_IN_SPECIES_LOADED: 'MOST_APPEARED_IN_SPECIES_LOADED',
    LONGEST_OPENING_CRAWL_LOADED: 'LONGEST_OPENING_CRAWL_LOADED',
    LARGEST_VEHICLE_PILOT_LOADED: 'LARGEST_VEHICLE_PILOT_LOADED',
    ADD_LOADING_A_QUESTION: 'ADD_LOADING_A_QUESTION',
    ERASE_QUESTIONS: 'ERASE_QUESTIONS'
}