export const actions = {
    LOAD_MOST_APPEARED_PERSON: 'LOAD_MOST_APPEARED_PERSON',
    LOAD_MOST_APPEARED_IN_SPECIES: 'LOAD_MOST_APPEARED_IN_SPECIES',
    LOAD_LONGEST_OPENING_CRAWL: 'LOAD_LONGEST_OPENING_CRAWL',
    ERASE_QUESTIONS: 'ERASE_QUESTIONS'
}